#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 003: Sibling Leaderboards & Friendly Competition

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec 003: Sibling Leaderboards"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Navigate to project root
cd /Users/fredriksafsten/Projects/teacher

# Backend API Server (TypeScript/Express)
echo ""
echo -e "${YELLOW}Starting Backend API...${NC}"
cd backend
npm run dev > ../logs/backend.log 2>&1 &
BACKEND_PID=$!
cd ..

wait_for_service 6001 "Backend API"

# Frontend Server (Next.js)
echo ""
echo -e "${YELLOW}Starting Frontend...${NC}"
cd frontend
npm run dev > ../logs/frontend.log 2>&1 &
FRONTEND_PID=$!
cd ..

wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:6001/api"
echo "  Frontend:     http://localhost:3000"
echo ""
echo "Database:"
echo "  SQLite: data/teacher.db"
echo ""
echo "Logs:"
echo "  Backend:  logs/backend.log"
echo "  Frontend: logs/frontend.log"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""
echo "Feature: Sibling Leaderboards & Friendly Competition"
echo "  - Family-only leaderboards with parent controls"
echo "  - Weekly and all-time rankings"
echo "  - Family challenges with bonus rewards"
echo ""
echo "========================================"
