-- Curriculum Tag Fixes Migration
-- Generated by Opus 4.5 audit on 2026-01-05
-- 
-- This migration fixes incorrect LGR22 curriculum code assignments
-- identified through systematic analysis of all 475 problems.
--
-- Key patterns fixed:
-- 1. MA-SAN-04 (combinatorics) used for division/fraction problems
-- 2. MA-GEO-03 (position words) used for area/perimeter problems  
-- 3. MA-ALG-02 (patterns) used for arithmetic problems
-- 4. MA-TAL-03 (fractions/parts) used for simple arithmetic
-- 5. Grade-level mismatches (e.g., MA-GEO-07 for grade 3)

-- ============================================================================
-- Package: Piraternas Matematiska Skattjakt (Grade 6)
-- ============================================================================

-- Problem 1: "840 guldmynt... dela upp mellan 6 personer" = DIVISION
-- Current: MA-SAN-04 (combinatorics) - WRONG
-- Correct: MA-PRO-06 (problem-solving with four operations)
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-PRO-06')
WHERE exercise_id = '9a664960-313c-4f33-9d33-d7a6e89d171f' 
  AND exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-SAN-04');

-- Problem 2: "12.5m × 8.3m area" = AREA CALCULATION
-- Current: MA-GEO-08 (scale) - WRONG  
-- Correct: MA-GEO-07 (area/perimeter methods)
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-GEO-07')
WHERE exercise_id = '29638a47-01a9-49e2-86a0-ed862d751ae6'
  AND exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-GEO-08');

-- Problem 3: "45% + 30% + ? = 100%" = PERCENTAGE
-- Current: MA-ALG-05 (number patterns) - WRONG
-- Correct: MA-TAL-07 (percentages and their relation to fractions/decimals)
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-TAL-07')
WHERE exercise_id = '9ff219e7-a07f-4382-afc3-2d62c7abf342'
  AND exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-ALG-05');

-- Problem 4: "3/4 av 200 mynt" = FRACTIONS
-- Current: MA-SAN-04 (combinatorics) - WRONG
-- Correct: MA-TAL-06 (fractions and decimals)
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-TAL-06')
WHERE exercise_id = '7c27db3b-6745-4517-9723-d90131ea4000'
  AND exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-SAN-04');

-- Problem 5: "säljer hälften, får 75 mynt, hur många hade han?" = EQUATION
-- Current: MA-ALG-05 (patterns) - WRONG
-- Correct: MA-ALG-04 (equation solving methods)
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-ALG-04')
WHERE exercise_id = 'a98bc1aa-1363-4528-adcf-6931f9d09213'
  AND exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-ALG-05');


-- ============================================================================
-- Package: Mario & Spöken: Matematiska Äventyr (Grade 3)
-- ALL 10 problems incorrectly tagged as MA-TAL-03 (fractions)
-- These are all basic arithmetic word problems → should be MA-PRO-03
-- ============================================================================

-- Problem 1: "6 + 4 guldmynt" = ADDITION
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-PRO-03')
WHERE exercise_id = (SELECT id FROM package_problems WHERE question_text LIKE 'Mario samlar 6 guldmynt%' AND question_text LIKE '%Spöken%' LIMIT 1)
  AND exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-TAL-03');

-- Direct update by known IDs for Mario & Spöken package
-- (We'll use the package join to be precise)

UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-PRO-03')
WHERE exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-TAL-03')
  AND exercise_id IN (
    SELECT pp.id FROM package_problems pp
    JOIN math_packages mp ON pp.package_id = mp.id
    WHERE mp.name = 'Mario & Spöken: Matematiska Äventyr'
  );

-- ============================================================================
-- Package: Rymdpiraternas Matematiska Äventyr (Grade 3)  
-- ALL 10 problems incorrectly tagged as MA-TAL-03 (fractions)
-- These are all basic arithmetic word problems → should be MA-PRO-03
-- ============================================================================

UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-PRO-03')
WHERE exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-TAL-03')
  AND exercise_id IN (
    SELECT pp.id FROM package_problems pp
    JOIN math_packages mp ON pp.package_id = mp.id
    WHERE mp.name = 'Rymdpiraternas Matematiska Äventyr'
  );

-- ============================================================================
-- Package: Mario Matteäventyr (Grade 3)
-- ALL 5 problems incorrectly tagged as MA-ALG-02 (patterns)
-- These are all basic arithmetic word problems → should be MA-PRO-03
-- ============================================================================

UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-PRO-03')
WHERE exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-ALG-02')
  AND exercise_id IN (
    SELECT pp.id FROM package_problems pp
    JOIN math_packages mp ON pp.package_id = mp.id
    WHERE mp.name = 'Mario Matteäventyr'
  );

-- ============================================================================
-- Package: Mario Matemagi (Grade 3)
-- Problems incorrectly tagged with geometry codes for arithmetic
-- ============================================================================

-- Problem 1: "12 + 15 + 8 mynt" = ADDITION (not position words)
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-PRO-03')
WHERE exercise_id = '3c0b44a1-93fa-427c-abfd-b55013ac75d2'
  AND exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-GEO-03');

-- Problem 2: "4 svampar / 2 personer" = DIVISION (not position words)
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-TAL-03')
WHERE exercise_id = 'ab1e9d75-3875-4e84-8112-41daa0e1c373'
  AND exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-GEO-03');

-- Problem 3: "6 × 3 block" = MULTIPLICATION (not symmetry)
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-PRO-03')
WHERE exercise_id = 'e9f5af24-cae0-4207-97de-6d0aaf772878'
  AND exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-GEO-04');


-- ============================================================================
-- Package: Dinosauriers Piratäventyr med Mario (Grade 3)
-- Mixed incorrect codes
-- ============================================================================

-- Problem 2: "7m × 4m area" = AREA (not position words)
-- For grade 3, area problems should use MA-GEO-01 (basic geometric objects)
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-GEO-01')
WHERE exercise_id = '6bd1164c-7ad4-42e2-8b72-a3c8b595de03'
  AND exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-GEO-03');

-- Problem 3: "1/3 av 45" = FRACTIONS (not patterns)
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-TAL-03')
WHERE exercise_id = '1b94c9cf-5ef2-4444-8a48-6e1a1b3fbea5'
  AND exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-ALG-02');

-- Problem 5: "12 + 18 fotografier" = ADDITION (not fractions)
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-PRO-03')
WHERE exercise_id = '1cb71f86-c27e-4f66-8b0f-123094097eb4'
  AND exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-TAL-03');

-- Problem 6: "kvadrat sidan 5m, omkrets" = PERIMETER (not position words)
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-GEO-01')
WHERE exercise_id = '99be3ba7-1fe6-49e9-8b4f-2f1d3f2e53d3'
  AND exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-GEO-03');

-- Problem 7: "72 / 9" = DIVISION (not patterns)
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-TAL-03')
WHERE exercise_id = 'b2ea8ee6-c9a6-498c-8ed4-f723d106c7e5'
  AND exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-ALG-02');

-- Problem 8: "3m × 5m area" = AREA (not position words)
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-GEO-01')
WHERE exercise_id = '16d20394-69fb-47fe-b57f-0193f4f9b791'
  AND exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-GEO-03');

-- Problem 9: "24 × 3 kg" = MULTIPLICATION (not fractions)
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-PRO-03')
WHERE exercise_id = '88783c33-a00c-456d-aa06-282d8a02a91d'
  AND exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-TAL-03');

-- ============================================================================
-- Package: Geometri och Tal - Årskurs 3 (Kjell-Gunbritts Lego-Fängelse)
-- Check for MA-TAL-04 which is grade 4-6 code used in grade 3 package
-- ============================================================================

-- Fix any MA-TAL-04 (grade 4-6) used in grade 3 → should be MA-TAL-01 or MA-TAL-03
UPDATE exercise_curriculum_mapping
SET objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-TAL-01')
WHERE exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-TAL-04')
  AND exercise_id IN (
    SELECT pp.id FROM package_problems pp
    JOIN math_packages mp ON pp.package_id = mp.id
    WHERE mp.grade_level = 3
  );

-- ============================================================================
-- Fix any MA-GEO-07 (grade 4-6 area/perimeter) used in grade 3 packages
-- These problems already have MA-GEO-01, so DELETE the incorrect MA-GEO-07 mapping
-- ============================================================================

DELETE FROM exercise_curriculum_mapping
WHERE exercise_type = 'package_problem'
  AND objective_id = (SELECT id FROM curriculum_objectives WHERE code = 'MA-GEO-07')
  AND exercise_id IN (
    SELECT pp.id FROM package_problems pp
    JOIN math_packages mp ON pp.package_id = mp.id
    WHERE mp.grade_level = 3
  );


-- ============================================================================
-- VERIFICATION QUERIES (run after migration to confirm changes)
-- ============================================================================

-- Verify Piraternas Matematiska Skattjakt now has correct codes
-- SELECT pp.problem_number, co.code, co.description
-- FROM package_problems pp
-- JOIN math_packages mp ON pp.package_id = mp.id
-- JOIN exercise_curriculum_mapping ecm ON ecm.exercise_id = pp.id
-- JOIN curriculum_objectives co ON ecm.objective_id = co.id
-- WHERE mp.name = 'Piraternas Matematiska Skattjakt'
-- ORDER BY pp.problem_number;

-- Count problems by package that still have potential issues
-- (MA-SAN-04 used without "kombination" or "sätt" in question)
-- SELECT mp.name, COUNT(*) as count
-- FROM package_problems pp
-- JOIN math_packages mp ON pp.package_id = mp.id
-- JOIN exercise_curriculum_mapping ecm ON ecm.exercise_id = pp.id
-- JOIN curriculum_objectives co ON ecm.objective_id = co.id
-- WHERE co.code = 'MA-SAN-04'
--   AND pp.question_text NOT LIKE '%kombination%'
--   AND pp.question_text NOT LIKE '%olika sätt%'
--   AND pp.question_text NOT LIKE '%hur många sätt%'
-- GROUP BY mp.name;

